project:
  type: website
  output-dir: docs

website:
  title: My Website
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: R
        contents: 
          - page1.qmd
      - section: Julia
        contents:
          - page2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto